//
// Copyright (c) Vatsal Manot
//

import Foundation

extension Perplexity.APISpecification.ResponseBodies {
    public struct ChatCompletion: Codable, Hashable, Sendable {
        
        public struct Choice: Codable, Hashable, Sendable {

            public enum FinishReason: String, Codable, Hashable, Sendable {
                case stop
                case length
            }

            public let index: Int
            
            /// The message generated by the model.
            public let message: Perplexity.ChatMessage
            
            /// The reason the model stopped generating tokens. Possible values include stop if the model hit a natural stopping point, or length if the maximum number of tokens specified in the request was reached.
            public let finishReason: FinishReason
            
            /// The incrementally streamed next tokens. Only meaningful when stream = true.
            public let delta: Perplexity.ChatMessage
        }
        
        public struct Usage: Codable, Hashable, Sendable {
            /// The number of tokens provided in the request prompt.
            public let promptTokens: Int
            
            /// The number of tokens generated in the response output.
            public let completionTokens: Int
            
            /// The total number of tokens used in the chat completion (prompt + completion).
            public let totalTokens: Int
        }
        
        /// An ID generated uniquely for each response.
        public var id: String
        
        /// The object type, which always equals chat.completion.
        public var object: String
        
        /// The Unix timestamp (in seconds) of when the completion was created.
        public var created: Date
        
        /// The model used to generate the response.
        public var model: String
        
        /// The list of completion choices the model generated for the input prompt.
        public var choices: [Choice]
        
        /// Usage statistics for the completion request.
        public let usage: Usage
    }
}
